# Generated by Django 5.0.7 on 2024-08-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ruoli',
            },
        ),
    ]
